# Checkov configuration for AWS Secure Landing Zone
# Simplified configuration compatible with GitHub Actions checkov-action

# Framework to scan
framework:
  - terraform

# Compact output
compact: true

# Skip specific checks that are handled at organization level or not applicable
skip-check:
  - CKV_AWS_21  # S3 bucket versioning - handled centrally
  - CKV_AWS_76  # VPC flow logs - centrally managed
  - CKV_AWS_144 # Ensure S3 bucket has cross-region replication - optional feature
  - CKV_AWS_18  # S3 access logging - handled at organization level

# Exclude paths from scanning
skip-path:
  - .terraform/
  - .git/
  - tests/
  - examples/